name: Docker Image CI

on:
  push:
    branches: [ "working" ]
  pull_request:
    branches: [ "working" ]
  workflow_dispatch:  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#    - uses: actions/setup-python@v5.1.0
 #     with: 
  #      python-version: 3.10
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 #   - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: tygozwolle/local-gpt:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
